# Generated by Django 5.0 on 2024-01-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
