# Generated by Django 5.0 on 2024-01-23 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 23, 17, 59, 44, 65106, tzinfo=datetime.timezone.utc)),
        ),
    ]
