# Generated by Django 5.0 on 2024-01-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_remove_order_address_remove_order_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
