# Generated by Django 5.0 on 2024-01-23 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_alter_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(verbose_name=datetime.datetime(2024, 1, 23, 18, 3, 53, 419240, tzinfo=datetime.timezone.utc)),
        ),
    ]
