# Generated by Django 5.0 on 2024-01-24 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_alter_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 8, 11, 38, 670615, tzinfo=datetime.timezone.utc)),
        ),
    ]
