# Generated by Django 5.0 on 2024-01-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
